### ISSUE TITLE
"CSV" Export Fails in SPFx in SharePoint Online outside of Workbench due to SharePoint link manipulation

### ISSUE THREAD

**Issue by tandrasi** [microsoft/FluentUIEditableDetailsList#103]
Hi,

Came across an issue where SharePoint Online refuses to download the BLOB created when exporting a CSV from the editable grid. This happens on a live site and NOT in the workbench (using SPFx). 

**The issue is easy to fix and I've got a working fix** but don't quite know how to use Github for pull requests etc.

The issue stems from SharePoint's link manipulation. To disable it, use the attribute **data-interception="off"** on links so SharePoint forgoes any attempts at intercepting their original intent (i.e. generating BLOBs or even opening links up in new tabs). This is what's causing the CSV download to fail.

![image](https://user-images.githubusercontent.com/72114492/158095432-bc23acfb-d482-4796-bf50-36f27fd6ba7e.png)

All that is needed is:

1. Go to line # 42 in **gridexportutil.tsx**
2. Add in :
`link.dataset.interception = 'off';`

There is a similar issue reported here for a separate tool - basically just any custom "csv" export.
https://github.com/SharePoint/sp-dev-docs/issues/4958

**Comment by kushalmehrotra713** [comment]
Hi @tandrasi 
Thanks for pointing this out and providing the fix for this. You can find the fix in PR https://github.com/microsoft/FluentUIEditableDetailsList/pull/104

Also, the same has been updated in npm package as well. 
Kindly verify.

**Comment by tandrasi** [comment]
Yes thank you so much, I can confirm this is fixed in the latest release!
