### ISSUE TITLE
Clicking on "Bulk Edit" causes TypeError: Cannot read properties of undefined (reading 'setExtraStackFrame') | react-jsx-runtime.development.js | happens ONLY when serving my SPFx project in development mode

### ISSUE THREAD

**Issue by tandrasi** [microsoft/FluentUIEditableDetailsList#112]
Currently I'm using SPFx v1.14.0. Clicking on "Bulk Edit" after selecting a row, with at least one editable column, I get the below error. I think there might be an **environment mismatch when building/compiling the code via Babel.** 

Please note that this **does not** happen with the source code when running "npm start" and works perfectly.

    Uncaught TypeError: Cannot read properties of undefined (reading 'setExtraStackFrame')
    at setCurrentlyValidatingElement$1 (react-jsx-runtime.development.js:872:1)
    at validateExplicitKey (react-jsx-runtime.development.js:984:1)
    at validateChildKeys (react-jsx-runtime.development.js:1013:1)
    at jsxWithValidation (react-jsx-runtime.development.js:1184:1)
    at jsxWithValidationDynamic (react-jsx-runtime.development.js:1209:1)
    at EditPanel (editpanel.js:108:43)
    at Yr (sp-pages-assembly_en-au_0a4bf7bfd698a9ad6d065bd3d5080219.js:69:63936)
    at Ro (sp-pages-assembly_en-au_0a4bf7bfd698a9ad6d065bd3d5080219.js:69:72775)
    at ys (sp-pages-assembly_en-au_0a4bf7bfd698a9ad6d065bd3d5080219.js:69:111038)
    at pc (sp-pages-assembly_en-au_0a4bf7bfd698a9ad6d065bd3d5080219.js:69:102601)

 This happens either when I publish my code to the AppCatalog in SharePoint or via "gulp serve" mode.

I noticed this project uses React 17.0.2+. With SPFx, I'm currently stuck at, but don't know if that impacts this.

    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8"

Now, I've tried this with the current latest repo code **in addition** to a forked repo I'm working on (built via "npm run build") and I get the same result.

Could anyone please help with this?

**EDIT: PLEASE SEE MY NEW COMMENT BELOW**

**Comment by tandrasi** [comment]
OK, after a total fluke I realise that is only happens when running "gulp serve" on my SPFx app (aka running in 'development' mode). This does not happen when we build the SFPx project and deploy (aka production).

So this is extremely low priority, but just putting it out there.

**Comment by kushalmehrotra713** [comment]
Hi @tandrasi 
Thanks for raising this. Unfortunately, due to personal exigencies, I have not been able to spend any time on this or editable grid in general of late. 
There are a bunch of new features and bug fixes in the pipeline but I will only be able to start on that after mid-June. Appreciate your patience and thanks for all your co-operation on this and other open issues.

**Comment by tandrasi** [comment]
> Hi @tandrasi Thanks for raising this. Unfortunately, due to personal exigencies, I have not been able to spend any time on this or editable grid in general of late. There are a bunch of new features and bug fixes in the pipeline but I will only be able to start on that after mid-June. Appreciate your patience and thanks for all your co-operation on this and other open issues.

@kushalmehrotra713 not a problem at all. I am going hard with development as we have a client project we're getting out the door. **I would love for you to see the final updates** we end up making and have a discussion as they are really extend the functionality quite substantially. Would be good to see what is on your pipeline vs what we develop! The fork is here https://github.com/infexious-dev/FluentUIEditableDetailsList and I'm updating the Readme file with all changes/updates I've made.

Take this for example. A small part of the current overall changes. Ability to add in sticky content above and below the grid content...allowing it to be contained within the scrollable pane. This is done via the ScrollablePane ref.

![Sticky Content](https://user-images.githubusercontent.com/72114492/167778535-8ed26f49-527a-4dbb-9e0f-35218a96e6c7.png)

**Comment by tandrasi** [comment]
Turns out this is an issue with SPFx itself and I fixed it coincidentally by fixing another issue whereby ReactDOMServer functions were failing in development mode.

Find the issue and **workaround** here:

https://github.com/SharePoint/sp-dev-docs/issues/7033
