### ISSUE TITLE
Unable to extend command bar

### ISSUE THREAD

**Issue by camer314** [microsoft/FluentUIEditableDetailsList#128]
Would be really great if you allowed us to add additional buttons to the command bar. For example, I want to be able to support pasting data from Excel and, although I could handle the event myself it would be nice to have the option to add this to the command bar so I could present a dialog.

**Comment by kushalmehrotra713** [comment]
Hi @camer314,
This is possible. I can plug this functionality in the grid by weekend. Please watch this thread for further info.

**Comment by kushalmehrotra713** [comment]
Hi @camer314,
The PR https://github.com/microsoft/FluentUIEditableDetailsList/pull/129 introduces the feature to extend command bar. Please try it out. Closing this issue for now. Please feel free to reopen it if need be. Thanks
