### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by unseen1980** [microsoft/FluentUIEditableDetailsList#15]
Hi, thanks for the very useful component.

I would like to ask you if you plan to publish an npm package? If yes do you know the timeframe?

@kushalmehrotra713 

Regards
Christos

**Comment by kushalmehrotra713** [comment]
Hi Christos,
Glad that you find the component useful.

I was planning to go about the npm publishing on a need basis. Now that you mentioned it, I can plan to publish it in 2 week's time. 

Regards,
Kushal

**Comment by unseen1980** [comment]
@kushalmehrotra713  That would be great! Otherwise I would have to fork it. 
Thanks!

**Comment by viktorsteinwand** [comment]
Hi @kushalmehrotra713, big thanks for the component! It would be really great if we could pull this component from the official npm registry :-) When do you plan to publish it on npm?

Many thanks
Viktor

**Comment by pksorensen** [comment]
We are also looking at this, could someone outline the steps needed for me to use this in a project?

How do output a package that i can consume from my own project that uses latest fluentui react package?

**Comment by nikki9696** [comment]
We would also love it if this was in npm. One of the biggest hurdles for us with trying to use Fluent UI for our new project is the lack of an editable, exportable data grid. DetailsList alone just isn't cutting it. This is super neat.

**Comment by kushalmehrotra713** [comment]
Hi @unseen1980 , @viktorsteinwand  , @pksorensen  , @nikki9696 
Apologies for the delay in this. I will be publishing npm package for the grid in the next 2 days. I will notify it in the same space and will be closing this issue after publish.

Thanks,
Kushal

**Comment by kushalmehrotra713** [comment]
> Hi @unseen1980 , @viktorsteinwand , @pksorensen , @nikki9696
> Apologies for the delay in this. I will be publishing npm package for the grid in the next 2 days. I will notify it in the same space and will be closing this issue after publish.
> 
> Thanks,
> Kushal

Hi @unseen1980 @viktorsteinwand @pksorensen @nikki9696 ,
Npm package for this grid can be found at https://www.npmjs.com/package/fluentui-editable-grid.

Installation: 
> npm i fluentui-editable-grid

Please refer to the documentation on the npm page to get you started and do let me know if there are any bugs/feature requests that need to addressed. I am closing this issue now.
Cheers.
