### ISSUE TITLE
Unable to use the EditableDetailsGrid inside PCF Framework

### ISSUE THREAD

**Issue by nimitbhardwaj** [microsoft/FluentUIEditableDetailsList#44]
I am working on [Microsoft's PCF framework](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview) (you can see the tutorial [here](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)), and normally I can easily use the other FleuentUI components in the framework without any errors, but I have a requirement for EditableDetailsGrid, and I am not able to use it, I am getting following error.

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```
I think, I am doing everything fine here, I double checked all the points mentioned here, but still getting the error.

**Comment by kushalmehrotra713** [comment]
> I am working on [Microsoft's PCF framework](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview) (you can see the tutorial [here](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)), and normally I can easily use the other FleuentUI components in the framework without any errors, but I have a requirement for EditableDetailsGrid, and I am not able to use it, I am getting following error.
> 
> ```
> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> ```
> 
> I think, I am doing everything fine here, I double checked all the points mentioned here, but still getting the error.

Hi @nimitbhardwaj . EditableGrid component has not been tested with powerapps yet. But in order to get a better understanding, could you post some sample code of how you would consume a normal DetailsList component in pcf and also how you are consuming the EditbaleGrid component in your code?

**Comment by kushalmehrotra713** [comment]
> I am working on [Microsoft's PCF framework](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview) (you can see the tutorial [here](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)), and normally I can easily use the other FleuentUI components in the framework without any errors, but I have a requirement for EditableDetailsGrid, and I am not able to use it, I am getting following error.
> 
> ```
> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> ```
> 
> I think, I am doing everything fine here, I double checked all the points mentioned here, but still getting the error.

Hi @nimitbhardwaj . EditableGrid component has not been tested with powerapps yet. But in order to get a better understanding, could you post some sample code of how you would consume a normal DetailsList component in pcf and also how you are consuming the EditbaleGrid component in your code?

**Comment by kushalmehrotra713** [comment]
Hi @nimitbhardwaj. Since I haven't received any response on this, I will be closing this issue for now.
