### ISSUE TITLE
Resetting items state isn't reflected in the EditableGrid

### ISSUE THREAD

**Issue by JamesCrawley** [microsoft/FluentUIEditableDetailsList#56]
If I have this component set up, where `myItems` is a piece of React State:

```
export default ({ myItems }) => {
  console.log({ myItems })

  return (
    <EditableGrid
      items={myItems}
      // ... rest of the props
    />
  )
}
```
The `EditableGrid` displays the items correctly, however setting myItems to an empty array (through the use of a button click separate to this library) re-renders this component and logs `myItems` as an empty array as you'd expect, but the `EditableGrid` stays populated with the now non-existent data.

Try changing `EditableGrid` to `DetailsList`, and you should see the expected behaviour of the `DetailsList` updating to display no data

**Comment by JamesCrawley** [comment]
It appears this is caused by [this line](https://github.com/microsoft/FluentUIEditableDetailsList/blob/main/src/libs/editablegrid/editablegrid.tsx#:~:text=props.items.length%20%3E%200), whether or not removing it would break other functionality I'm not sure

**Comment by kushalmehrotra713** [comment]
Hi @JamesCrawley . Thanks for pointing out the bug. I have fixed it and merged in the latest PR.

**Comment by kushalmehrotra713** [comment]
Hi @JamesCrawley 
Closing this issue now since it has been fixed. Please feel free to open another thread if the issue exists
