### ISSUE TITLE
A way to put the grid in standard edit mode?

### ISSUE THREAD

**Issue by MarkoKosmajac** [microsoft/FluentUIEditableDetailsList#70]
Hi,

I've been looking for some time now, for a way to simulate or to just put the grid in edit mode upon rendering. I don't find any options in the codebase to do this. Will this be added? When the grid is rendered I need people to be immediately able to fill in fields and just press 1 save button.

Thanks

**Comment by kushalmehrotra713** [comment]
Hi @MarkoKosmajac .
Currently the grid does not support default edit mode rendering. But given that it can be a common use case, let me try spinning something around this in the coming week. Kindly watch this thread for more updates.

**Comment by MarkoKosmajac** [comment]
Hi @kushalmehrotra713 , thanks a lot for your answer! I'm looking forward :)

**Comment by kushalmehrotra713** [comment]
Hi @MarkoKosmajac 
Please check the Pull Request https://github.com/microsoft/FluentUIEditableDetailsList/pull/76 which introduces this feature. In order for you to enable this feature, you need to add the attribute enableDefaultEditMode={true} to the Grid. Kindly let me know if this works out for you.

**Comment by MarkoKosmajac** [comment]
Yes, it works, thanks!
