### ISSUE TITLE
Navigate to next cell when TAB is pressed

### ISSUE THREAD

**Issue by MarkoKosmajac** [microsoft/FluentUIEditableDetailsList#75]
Hi,

Is there a way to go to the next row and fill in the next value [EDITFIELD] when TAB or ENTER or a specific key is pressed?
![tabpress](https://user-images.githubusercontent.com/43277934/149783348-7b8fc6d8-1459-4f51-87a8-64e638b5edb1.png)

**Comment by kushalmehrotra713** [comment]
Hi @MarkoKosmajac 
You can navigate to the next row with down arrow and navigate to controls in the same row using left and right arrows. Please note that this is the default accessibility behavior of Detailslist.

**Comment by kushalmehrotra713** [comment]
Hi @MarkoKosmajac 
You can navigate to the next row with down arrow and navigate to controls in the same row using left and right arrows. Please note that this is the default accessibility behavior of Detailslist.

**Comment by MarkoKosmajac** [comment]
Ok, thanks, I didn't know this!
