### ISSUE TITLE
On textfield, cursor jumps after every input change

### ISSUE THREAD

**Issue by vuciv** [microsoft/FluentUIEditableDetailsList#96]
I have tried removing the `multiline={true}` from the EditControlType.MultilineTextField's render method, and this seems to stop the problem from happening. But obviously, I can't get a multiline text field that way. Has anyone encountered this?

```javascript
                                <TextField
                                errorMessage={activateCellEdit[rowNum!]['properties'][column.key].error}
                                label={item.text}
                                ariaLabel={column.key}
                                //multiline={true} // this line seems to be causing the issue
                                rows={1}
                                styles={textFieldStyles}
                                onChange={(ev, text) => onCellValueChange(ev, text!, item, rowNum!, column.key, column)}
                                autoFocus={true && !editMode && !(activateCellEdit && activateCellEdit[Number(item['_grid_row_id_'])!] && activateCellEdit[Number(item['_grid_row_id_'])!]['isActivated'])}
                                value={activateCellEdit[rowNum!]['properties'][column.key].value}
                                maxLength={column.maxLength != null ? column.maxLength : 10000}
                                />
```

EDIT: I have discovered that my cursor is also jumping to the end if multiline is not there. So, this is an issue not specific to multiline, but hopefully gives a clue as to what is going on.

**Comment by kushalmehrotra713** [comment]
Hi @vuciv 
If I understand the issue correctly, you say that the input cursor for Multiline TextField returns to the beginning of the textfield control after every input. Is that understanding correct?
Unfortunately, I am not able to reproduce this issue. Are you facing the same issue here? https://editabledetailslist.azurewebsites.net/

Can you guide me through the steps to repro this issue?
